spring:
    kafka:
        bootstrap-servers: ${CLOUDKARAFKA_BROKERS}
        properties:
            sasl:
                jaas:
                    config: org.apache.kafka.common.security.scram.ScramLoginModule
                        required username="${CLOUDKARAFKA_USERNAME}" password="${CLOUDKARAFKA_PASSWORD}";
                mechanism: SCRAM-SHA-256
            security:
                protocol: SASL_SSL
